name: qt_easytier_mobile
description: QtEasyTier Mobile - 基于 Flutter 的 EasyTier 组网客户端
publish_to: 'none'
version: 1.0.0+4003

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  ffi: ^2.1.0
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
